import random
import os
import httpx

def heuristic_ai_detect(text: str) -> dict:
    # Basic heuristic: calculate average sentence length and vocabulary richness
    # This is a dummy implementation. A real one would use a model like RoBERTa.
    words = text.split()
    if not words:
        return {"aiProbability": 0.0, "report": "No text provided."}
    
    # Pseudo-random logic based on length for demonstration
    length = len(words)
    prob = min(0.95, max(0.05, (length % 100) / 100.0))
    
    return {
        "aiProbability": prob,
        "report": f"Based on structural analysis, there is a {int(prob*100)}% chance this text was generated by AI."
    }

def heuristic_summarize(text: str, options: dict) -> str:
    # Very basic summarizing: just return the first two sentences
    sentences = text.replace('!', '.').replace('?', '.').split('.')
    sentences = [s.strip() for s in sentences if s.strip()]
    if not sentences:
        return ""
    if len(sentences) <= 2:
        return text
    return sentences[0] + ". " + sentences[1] + "."

def heuristic_paraphrase(text: str, style: str) -> str:
    # A dummy paraphrasing that just adds some words
    if not text.strip():
        return ""
    words = text.split()
    if len(words) < 3:
        return text
    return "In other words, " + text

def heuristic_grammar(text: str) -> dict:
    # Dummy grammar check
    issues = []
    if "  " in text:
        issues.append("Double spaces found.")
    return {
        "issues": issues,
        "message": "Grammar check complete. Found {} issues.".format(len(issues))
    }
